name: Build and Deploy Docker App

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t ganeshdatti76/myapp:latest .

    - name: Push Docker Image
      run: docker push ganeshdatti76/myapp:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          docker pull ganeshdatti76/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d -p 9000:3000 --name myapp ganeshdatti76/myapp:latest
